
#ccflags-y += -DCOMPATIBLE_IN_HAL
ccflags-y += -DPLATFORM_QCOM

# -w -Wno-strict-aliasing -Wno-error=unused-function -Wno-error=unused-label -Wno-warning=unused-function -Wno-warning=unused-label
ccflags-y += -Wno-unused-label -Wno-unused-variable
obj-$(CONFIG_BETTERLIFE_FINGERPRINT) += bf_fp_platform.o